name: hashtara
description: A social networking app with Cupertino design
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # 상태 관리
  flutter_riverpod: ^2.4.9
  
  # Firebase - 버전 업데이트됨
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.15
  firebase_app_check: ^0.2.2+7
  firebase_analytics: ^10.4.4
  
  # 구글 로그인
  google_sign_in: ^6.2.1
  
  # 이미지 관련
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  flutter_svg: ^2.0.9
  
  # 유틸리티
  intl: ^0.19.0
  uuid: ^4.2.2
  path_provider: ^2.1.2
  shared_preferences: ^2.5.3
  logger: ^2.0.2+1
  share_plus: ^7.2.1
  clipboard: ^0.1.3
  path: ^1.8.3
  rxdart: ^0.28.0
  flutter_local_notifications: ^19.2.1
  timeago: ^3.7.1
  permission_handler: ^11.3.1
  url_launcher: ^6.2.5

  
  # UI 관련
  shimmer: ^3.0.0
  pull_to_refresh_flutter3: ^2.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1  # 앱 아이콘 생성을 위한 패키지 추가

# 앱 아이콘 설정
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"  # 안드로이드 어댑티브 아이콘 배경색
  adaptive_icon_foreground: "assets/images/icon.png"  # 안드로이드 어댑티브 아이콘 포그라운드
  min_sdk_android: 21  # 안드로이드 최소 SDK 버전
  remove_alpha_ios: true  # iOS에서 알파 채널 제거 (불투명 배경 필요)
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#ffffff"
    theme_color: "#000000"
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro-Italic.ttf
          weight: 400
          style: italic